# Numpy {#numpy}
Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays

<iframe src="https://numpy.org/doc/stable/user/absolute_beginners.html" height="500px" width="95%"></iframe>

## Arrays 
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers. 
The number of dimensions is the rank of the array.
The shape of an array is a tuple of integers giving the size (the total number of elements) of the array along each dimension.
```{python}
import numpy as np
```


```{python}
# 1-dimensonal array, also referred to as a vector
a1 = np.array([1, 2, 3])
a1.shape, a1.ndim, a1.dtype, a1.size, type(a1)
```

```{python}
# 2-dimensional array, also referred to as matrix
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a2.shape, a2.ndim, a2.dtype, a2.size, type(a2)
```


```{python}
# 3-dimensional array, also referred to as a matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])
a3.shape, a3.ndim, a3.dtype, a3.size, type(a3)
```

### Creating Arrays
* `np.array()`
* `np.ones()`
* `np.full()`
* `np.zeros()`
* `np.random.rand(5, 3)`
* `np.random.randint(10, size=5)`
* `np.random.seed()` - pseudo random numbers

You can change the data type with `.astype()` or calling the argument `dtype=` when creating. 
```{python}
# Create an array of ones, 10 rows of 2 cols type integer
ones = np.ones((10, 2))
# Create an array of zeros
zeros = np.zeros((5, 3, 3))
# One-dim array from 1 to 10
a = np.arange(1,11)
# One-dim array of 100 numbers from 1 to 10
a = np.linspace(1,11,50) 
# Random array of integers
a = np.random.randint(10, size=(5, 3))
# Random array of floats (between 0 & 1)
a = np.random.random((5, 3))
```
For consistency, you might want to keep the random numbers you generate similar throughout experiments. To do this, you can use [`np.random.seed()`](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.seed.html).

### Indexing and slicing arrays
Array shapes are always listed in the format `(row, column, n...)` where `n` is optional extra dimension(s).
```{python}
a = np.arange(100)
a = a.reshape(50,2)
a[0,1]  # same form of an access to a nested list or a[0][1] 
a[1:3]  # row slice
a[:,0]  # project on first column
a[0]    # first row or a[0, :]
a[:3,0] # Get the first value of the first 3 row
```

```{python}
b = np.arange(48).reshape(4, 12)
b, b[(0,2), 2:5],  b[:, (-1, 2, -1)]

# returns a 1D array with b[-1, 5], b[2, 9], b[-1, 1] and b[2, 9]
b[(-1, 2, -1, 2), (5, 9, 1, 9)]
```


### Reshape
```{python}
a = np.arange(0,11) 
## Reshape into n rows of n col
# Row vector
a = a.reshape((1,11)) #a[np.newaxis, :]
a
```
```{python}
# Column vector
a = a.reshape((11,1)) #a[:, np.newaxis]
a
```
```{python}
# Transpose the array
a.T
```

#### Aggregate
```{python}
#Concatenate (The arrays must have equal numbers of dimensions)
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
np.concatenate([a, b, c])
```
For arrays with different numbers of dimensions, use vstack and hstack to perform concatenation. The inverse operation, splitting, is implemented by split,vsplit,hsplit
```{python}
a = np.array([2,3,5])
b = np.array([[7,11,13], [17,19,23]])
np.vstack([a, b]) #np.concatenate((a, b), axis=0)
```
```{python}
b = np.array([[29], [31]])
b2 = np.array([[7,11,13], [17,19,23]])
np.hstack([b, b2]) ##np.concatenate((a, b), axis=1)
```
```{python}
a = np.array([2,3,5,7,11,13,17,19,23])
a1, a2, a3 = np.split(a, [3,6])
a1, a2, a3
```
There is also a split function which splits an array along any given axis. Calling vsplit is equivalent to calling split with axis=0. There is also an hsplit function, equivalent to calling split with axis=1.

#### Sort
* `np.sort()`
* `np.argsort()`
* `np.argmax()`
* `np.argmin()`

#### Transpose
The transpose method creates a new view on an ndarray’s data, with axes permuted in the given order. By default, transpose reverses the order of the dimensions:

```{python}
a = np.arange(24).reshape(4,2,3)
a
a2= a.transpose() # equivalent to t.transpose((2, 1, 0))
```

Now let’s create an ndarray such that the axes 0, 1, 2 (depth, height, width) are re-ordered to 1, 2, 0 (depth→width, height→depth, width→height):

```{python}
a1 = a.transpose((1,2,0))
a1, a1.shape
```

NumPy provides a convenience function `swapaxes()` to swap two axes. For example, let’s create a new view of t with depth and height swapped:
```{python}
a3 = a.swapaxes(0,1) # equivalent to a.transpose((1, 0, 2)) 
a3
```

The `T` attribute is equivalent to calling `transpose()` when the rank is 2. The T attribute has no effect on rank 0 (empty) or rank 1 arrays.

```{python}
a.T
```

## Operators
All the usual arithmetic operators can be used with ndarrays. They apply element wise:
* Arithmetic
    * `+`, `-`, `*`, `/`, `//`, `**`, `%`
    * `np.exp()`
    * `np.log()`
    * `np.dot()` - [Dot product](https://en.wikipedia.org/wiki/Matrix_multiplication)
    
The arrays must have the same shape. If they do not, NumPy will apply the *broadcasting rules*.

### Broadcasting Rules

* If the arrays do not have the same rank, then a 1 will be prepended to the smaller ranking arrays until their ranks match.

```{python}
h = np.arange(5).reshape(1, 1, 5)
h
```

Now let’s try to add a 1D array of shape (5,) to this 3D array of shape (1,1,5). Applying the first rule of broadcasting!

```{python}
h + [10, 20, 30, 40, 50] #same as: h + [[[10, 20, 30, 40, 50]]]
```

* Arrays with a 1, along a particular dimension, act as if they had the size of the array with the largest shape along that dimension. The value of the array element is repeated along that dimension.

```{python}
k = np.arange(6).reshape(2,3)
k
```
Let’s try to add a 2D array of shape (2,1) to this 2D ndarray of shape (2, 3). NumPy will apply the second rule of broadcasting:

```{python}
k + [[100], [200]] # same as: k + [[100, 100, 100], [200, 200, 200]]
```

Combining rules 1 & 2, we can do this:

```{python}
k + [100, 200, 300] # after rule 1: [[100, 200, 300]], and after rule 2:␣ 􏰰→[[100, 200, 300], [100, 200, 300]]
```

After rules 1 & 2, the sizes of all arrays must match.

```{python}
try:
 k + [33, 44]
except ValueError as e:
 print(e)
```

### Upcasting
When trying to combine arrays with different dtypes, NumPy will upcast to a type capable of handling all possible values (regardless of what the actual values are).

```{python}
k1 = np.arange(0, 5, dtype=np.uint8)
print(k1.dtype, k1)

k2 = k1 + np.array([5, 6, 7, 8, 9], dtype=np.int8)
# Note that int16 is required to represent all possible int8 and uint8 values (from -128 to 255)
print(k2.dtype, k2)

k3 = k1 + 1.5
print(k3.dtype, k3)
```

### Conditional operators
The conditional operators also apply elementwise.

* Comparison operators
    * `>`
    * `<`
    * `<=`
    * `>=`
    * `x != 3`
    * `x == 3`
    * `np.sum(x > 3)`
    
```{python}
k2 < np.array([2, 8, 11, 9, 6]) 
k2 < 8
```

### Statistics
Many mathematical and statistical functions are available for ndarrays.

* Aggregation
    * `np.sum()` - faster than `.sum()`
    * `np.prod()`
    * `np.mean()`
    * `np.std()`
    * `np.var()`
    * `np.min()`
    * `np.max()`
    * `np.argmin()` - find index of minimum value
    * `np.argmax()` - find index of maximum value

These functions accept an optional argument axis which lets you ask for the operation to be performed on elements along the given axis. For example:

```{python}
c=np.arange(24).reshape(2,3,4)
c
c.sum(axis=0) # sum across matrices
c.sum(axis=1) # sum across rows

c.sum(axis=(0,2)) # sum across matrices and columns (first row, second row , 8+9+10+11 + 20+21+22+23)
```

### Linear Algebra
Linear algebra functions are available in the *numpy.linalg* module. 
The `inv` function computes a square matrix’s inverse, whereas the `pinv()` computes the pseudoinverse.

```{python}
import numpy.linalg as linalg
a = np.array([[1,2,3],[5,7,11],[21,29,31]])
linalg.inv(a), linalg.pinv(a)
```
 
The qr function computes the QR decomposition of a matrix, also known as a QR factorization or QU factorization. It is a decomposition of a matrix A into a product A = QR of an orthogonal matrix Q and an upper triangular matrix R.

```{python}
q, r = linalg.qr(a)  #q.dot(r) -> q**r equals a
```

* The `det()` function computes the matrix determinant.
```{python}
linalg.det(a)
```

* The `eig()` function from `linalg` computes the eigenvalues and eigenvectors of a square matrix:
```{python}
eigenvalues, eigenvectors = linalg.eig(a)
eigenvalues, eigenvectors
```

* The `diag()` function returns the elements on the diagonal, whereas `trace()` returns their sum:
```{python}
np.diag(a),np.trace(a)
```
The solve function solves a system of linear scalar equations, such as:
$$2x+6y=6$$
$$5x+3y=-9$$
```{python}
coeffs  = np.array([[2, 6], [5, 3]])
depvars = np.array([6, -9])
solution = linalg.solve(coeffs, depvars)
solution
```

